### ISSUE TITLE
Upgrade to mkdocs 1.3.0

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/openstudiocoalition.github.io#9]
Even with a clean venv and installing mkdocs 0.11.0,  I can't build

```shell
$ cd markdown_source
$ mkdocs build
Traceback (most recent call last):
  File "/home/julien/Virtualenvs/mkdocs_osapp/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "/home/julien/Virtualenvs/mkdocs_osapp/lib/python3.7/site-packages/mkdocs/main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/home/julien/Virtualenvs/mkdocs_osapp/lib/python3.7/site-packages/mkdocs/main.py", line 35, in main
    config = load_config(options=options)
  File "/home/julien/Virtualenvs/mkdocs_osapp/lib/python3.7/site-packages/mkdocs/config.py", line 81, in load_config
    user_config = yaml.load(fp)
TypeError: load() missing 1 required positional argument: 'Loader'
```

Seems to be an issue because PyYAML is too new. The requirements.txt just freezes mkdocs to 0.11.0 but doesn't freeze the rest of the needed dependencies, so it's a nightmare to reproduce a virtualenv that works.

**Comment by jmarrec** [comment]
I pushed a WIP https://github.com/openstudiocoalition/openstudiocoalition.github.io/tree/mkdocs_130

I'm not going to bother trying to make it work. But we'll have the start of an upgrade if need be in the future

**Comment by jmarrec** [comment]
I managed to make 0.11.0 work by pinning to an older PyYAML and froze my entire virtualenv in #8, so at least the old mkdocs will be working in the mid term future, so this issue becomes (way) less important.
